TOPDIR ?= ../..
include $(TOPDIR)/.config

$(WTC_SUPPORT)_SRC += services/webTempClient/wtc.c
$(WTC_SUPPORT)_ECMD_SRC += services/webTempClient/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
